// <auto-generated />
namespace AstrophotographyBlog.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removechangestousermodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removechangestousermodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201710151447266_remove changes to user model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
