// <auto-generated />
namespace AstrophotographyBlog.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changestouserandpostmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changestouserandpostmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201710141454397_changes to user and post model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
